---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./apc1.yaml
  - ./apc2.yaml
  - ./apps.yaml
  - ./bazarr.yaml
  - ./calibre-web.yaml
  - ./calibre.yaml
  - ./chat.yaml
  - ./chat2.yaml
  - ./double-take.yaml
  - ./fireflyiii.yaml
  - ./frigate.yaml
  - ./kvm1.yaml
  - ./kvm2.yaml
  - ./kvm3.yaml
  - ./kvm4.yaml
  - ./kvm5.yaml
  - ./lidarr.yaml
  - ./localai.yaml
  - ./maybefinance.yaml
  - ./obico.yaml
  - ./octo.yaml
  - ./ollama.yaml
  - ./oods.yaml
  - ./overseerr.yaml
  - ./photoprism.yaml
  - ./plex.yaml
  - ./prowlarr.yaml
  - ./proxmox.yaml
  - ./radarr.yaml
  - ./readarr.yaml
  - ./sabnzbd.yaml
  - ./sonarr.yaml
  - ./switch.yaml
  - ./tautulli.yaml
  - ./transmission.yaml
  - ./unifi.yaml
  - ./unraid-portainer.yaml
  - ./unraid.yaml
